<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class SymptomSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        \DB::table('symptoms')->insert(
            [
                ['name' => 'Dor de cabeça', 'description' => 'Sensação de dor ou pressão na cabeça.'],
                ['name' => 'Febre', 'description' => 'Temperatura corporal acima do normal.'],
                ['name' => 'Tontura', 'description' => 'Sensação de desequilíbrio ou vertigem.'],
                ['name' => 'Náusea', 'description' => 'Vontade de vomitar ou mal-estar estomacal.'],
                ['name' => 'Vómitos', 'description' => 'Expulsão forçada do conteúdo do estômago.'],
                ['name' => 'Cansaço', 'description' => 'Sensação de fadiga ou falta de energia.'],
                ['name' => 'Dores musculares', 'description' => 'Desconforto ou dor nos músculos.'],
                ['name' => 'Dores articulares', 'description' => 'Dor nas articulações, como joelhos ou cotovelos.'],
                ['name' => 'Dor abdominal', 'description' => 'Dor localizada na região do abdómen.'],
                ['name' => 'Tosse', 'description' => 'Expulsão súbita de ar pelos pulmões.'],
                ['name' => 'Dificuldade para respirar', 'description' => 'Sensação de falta de ar.'],
                ['name' => 'Congestão nasal', 'description' => 'Nariz entupido ou obstruído.'],
                ['name' => 'Coriza', 'description' => 'Secreção líquida saindo do nariz.'],
                ['name' => 'Dor de garganta', 'description' => 'Irritação ou dor ao engolir.'],
                ['name' => 'Rouquidão', 'description' => 'Alteração na voz, tornando-a áspera ou fraca.'],
                ['name' => 'Perda de apetite', 'description' => 'Falta de vontade de comer.'],
                ['name' => 'Perda de peso', 'description' => 'Redução involuntária do peso corporal.'],
                ['name' => 'Aumento de peso', 'description' => 'Ganho excessivo de peso corporal.'],
                ['name' => 'Inchaço', 'description' => 'Aumento de volume em alguma parte do corpo.'],
                ['name' => 'Coceira', 'description' => 'Sensação que provoca vontade de coçar.'],
                ['name' => 'Erupções cutâneas', 'description' => 'Aparecimento de manchas ou lesões na pele.'],
                ['name' => 'Pele seca', 'description' => 'Ressecamento excessivo da pele.'],
                ['name' => 'Pele amarelada', 'description' => 'Tom amarelado da pele, comum em icterícia.'],
                ['name' => 'Visão turva', 'description' => 'Dificuldade para enxergar claramente.'],
                ['name' => 'Visão dupla', 'description' => 'Percepção duplicada de objetos.'],
                ['name' => 'Olhos vermelhos', 'description' => 'Irritação ocular com vermelhidão.'],
                ['name' => 'Lacrimejamento excessivo', 'description' => 'Produção aumentada de lágrimas.'],
                ['name' => 'Zumbido no ouvido', 'description' => 'Som constante no ouvido sem fonte externa.'],
                ['name' => 'Dor de ouvido', 'description' => 'Desconforto ou dor no ouvido.'],
                ['name' => 'Perda auditiva', 'description' => 'Diminuição da capacidade de ouvir.'],
                ['name' => 'Dor no peito', 'description' => 'Sensação de pressão ou dor na região torácica.'],
                ['name' => 'Palpitações', 'description' => 'Percepção do batimento cardíaco acelerado.'],
                ['name' => 'Tremores', 'description' => 'Movimentos involuntários e rítmicos.'],
                ['name' => 'Suor excessivo', 'description' => 'Transpiração acima do normal.'],
                ['name' => 'Calafrios', 'description' => 'Sensação de frio intenso com tremores.'],
                ['name' => 'Desmaios', 'description' => 'Perda temporária de consciência.'],
                ['name' => 'Confusão mental', 'description' => 'Dificuldade para pensar com clareza.'],
                ['name' => 'Ansiedade', 'description' => 'Sensação de preocupação ou nervosismo excessivo.'],
                ['name' => 'Depressão', 'description' => 'Tristeza persistente e perda de interesse.'],
                ['name' => 'Insónia', 'description' => 'Dificuldade para dormir ou permanecer dormindo.'],
                ['name' => 'Sonolência excessiva', 'description' => 'Tendência a dormir durante o dia.'],
                ['name' => 'Irritabilidade', 'description' => 'Facilidade em se irritar ou perder a paciência.'],
                ['name' => 'Perda de memória', 'description' => 'Esquecimento frequente de informações.'],
                ['name' => 'Dificuldade de concentração', 'description' => 'Problemas para manter o foco.'],
                ['name' => 'Convulsões', 'description' => 'Movimentos involuntários e perda de consciência.'],
                ['name' => 'Dormência', 'description' => 'Perda de sensibilidade em parte do corpo.'],
                ['name' => 'Formigamento', 'description' => 'Sensação de picadas ou agulhadas.'],
                ['name' => 'Rigidez muscular', 'description' => 'Dificuldade para mover músculos.'],
                ['name' => 'Fraqueza muscular', 'description' => 'Perda de força em membros.'],
                ['name' => 'Dor nas costas', 'description' => 'Desconforto ou dor na região lombar.'],
                ['name' => 'Dor no pescoço', 'description' => 'Desconforto na região cervical.'],
                ['name' => 'Dificuldade para engolir', 'description' => 'Sensação de bloqueio ao engolir.'],
                ['name' => 'Azia', 'description' => 'Sensação de queimação no estômago ou peito.'],
                ['name' => 'Refluxo', 'description' => 'Retorno do conteúdo do estômago ao esôfago.'],
                ['name' => 'Gases', 'description' => 'Acúmulo de ar no sistema digestivo.'],
                ['name' => 'Diarreia', 'description' => 'Evacuação frequente de fezes líquidas.'],
                ['name' => 'Prisão de ventre', 'description' => 'Dificuldade ou redução na evacuação.'],
                ['name' => 'Sangue nas fezes', 'description' => 'Presença de sangue ao evacuar.'],
                ['name' => 'Urina escura', 'description' => 'Coloração anormal da urina.'],
                ['name' => 'Dor ao urinar', 'description' => 'Sensação de ardor ou dor ao urinar.'],
                ['name' => 'Frequência urinária aumentada', 'description' => 'Necessidade de urinar frequentemente.'],
                ['name' => 'Retenção urinária', 'description' => 'Dificuldade em urinar.'],
                ['name' => 'Menstruação irregular', 'description' => 'Alterações no ciclo menstrual.'],
                ['name' => 'Cólicas menstruais', 'description' => 'Dor abdominal durante a menstruação.'],
                ['name' => 'Corrimento vaginal', 'description' => 'Secreção anormal proveniente da vagina.'],
                ['name' => 'Dor durante o sexo', 'description' => 'Desconforto ao ter relações sexuais.'],
                ['name' => 'Impotência sexual', 'description' => 'Dificuldade em manter ereção.'],
                ['name' => 'Perda de libido', 'description' => 'Redução do desejo sexual.'],
                ['name' => 'Nódulos na pele', 'description' => 'Pequenas elevações ou caroços na pele.'],
                ['name' => 'Feridas que não cicatrizam', 'description' => 'Lesões persistentes na pele.'],
                ['name' => 'Sangramento nasal', 'description' => 'Perda de sangue pelo nariz.'],
                ['name' => 'Sangramento gengival', 'description' => 'Sangramento das gengivas ao escovar os dentes.'],
                ['name' => 'Boca seca', 'description' => 'Falta de saliva na cavidade bucal.'],
                ['name' => 'Mau hálito', 'description' => 'Odor desagradável vindo da boca.'],
                ['name' => 'Inchaço nos pés', 'description' => 'Retenção de líquidos nos membros inferiores.'],
                ['name' => 'Varizes', 'description' => 'Veias dilatadas e visíveis nas pernas.'],
                ['name' => 'Pele pálida', 'description' => 'Perda de coloração normal da pele.'],
                ['name' => 'Batimentos cardíacos lentos', 'description' => 'Ritmo cardíaco abaixo do normal.'],
                ['name' => 'Batimentos cardíacos acelerados', 'description' => 'Ritmo cardíaco acima do normal.'],
                ['name' => 'Dor lombar', 'description' => 'Dor na parte inferior das costas.'],
                ['name' => 'Falta de ar ao esforço', 'description' => 'Dificuldade para respirar ao realizar atividades.'],
                ['name' => 'Tosse com catarro', 'description' => 'Tosse acompanhada de secreção.'],
                ['name' => 'Tosse seca', 'description' => 'Tosse sem produção de muco.'],
                ['name' => 'Pele fria e úmida', 'description' => 'Temperatura corporal fria com suor.'],
                ['name' => 'Sudorese noturna', 'description' => 'Suor excessivo durante o sono.'],
                ['name' => 'Perda de equilíbrio', 'description' => 'Dificuldade em manter-se estável.'],
                ['name' => 'Dificuldade para falar', 'description' => 'Problemas na articulação da fala.'],
                ['name' => 'Inchaço abdominal', 'description' => 'Aumento de volume na região abdominal.'],
                ['name' => 'Sede excessiva', 'description' => 'Necessidade constante de beber água.'],
                ['name' => 'Apetite excessivo', 'description' => 'Vontade anormal de comer.'],
                ['name' => 'Pele sensível', 'description' => 'Hipersensibilidade ao toque.'],
                ['name' => 'Manchas roxas', 'description' => 'Aparecimento de hematomas espontâneos.'],
                ['name' => 'Sensação de desmaio', 'description' => 'Tontura extrema com risco de perder a consciência.'],
                ['name' => 'Calafrios noturnos', 'description' => 'Sensação de frio durante a noite.'],
                ['name' => 'Enjoo matinal', 'description' => 'Náusea ao acordar.'],
                ['name' => 'Dificuldade para mover membros', 'description' => 'Rigidez ou fraqueza motora.'],
                ['name' => 'Pele azulada', 'description' => 'Coloração azulada devido à falta de oxigênio.'],
                ['name' => 'Pele avermelhada', 'description' => 'Aumento de fluxo sanguíneo na pele.'],
            ]
        );
    }
}
